Feature/channel
innovationCamp/messenger-service pull request #19
Opened 2023-08-07 02:58 UTC by KH-CHOO

2023-08-07 05:13 UTC, cornpip requested changes
코드리뷰

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/controller/ChannelController.java
swagger 라우트하고 메서드명 최신화해주세요!

{id} 는 {channelId} 가 혼동 없을 것 같아요

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/user/controller/UserController.java
> +    }
라우트, 메서드명 스웨거에 최신화 해주세요!

getChannelsUserJoined는 본인만 본인이 참여 중인 목록을 조회할테니까 {userId}는 없어도 될 것 같아요

해당 라우트 channel 도메인에 있는게 MSA 구상할 때 좋을 것 같아요
get /api/channel 은 어떨까요?

아니면 /api/channel/user -> /api/channel/member 로 하고
/api/channel/user로 써도 좋을 것 같아요

메서드명은 getAllChannelByUser 는 어떨까요?

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +    }
update 로직이 빠져있는 것 같아요

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +    @Transactional
@Transactional 이 필요할까요?

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +    @Transactional
여기도 @Transactional 이 필요할까요?

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +    }
@Transactional이 필요할까요?
채널에서 user를 내보내는 건 권한 확인 로직이 필요할 것 같아요

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +    }
채널에 user를 추가하는 건 일단 권한이 필요할 것 같아요

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +                })
.map(userChannel -> new UserChannelResponseDto(
                            userChannel.getChannel().getId(), userChannel.getReadTimestamp(), userChannel.isAdmin()
                    ))
중괄호 안 열어도 괜찮을 것 같아요

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +                            channelContent.getCalloutContent().getId(),
channelContent.getCalloutContent() 는 null일 수도 있지않나요?🤔

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/entity/ChannelContentType.java
> +    MESSAGE, CALL_OUT, FILE
CALL_OUT은 type과 무관할 것 같아요

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/entity/UserChannel.java
> +    private boolean isAdmin;
@Column 명시하는게 좋을 것 같아요

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/dto/ChannelContentResponseDto.java
> +    private final Long channelId;
채널을 특정 짓고 요청할테니까 channelId는 없어도 될 것 같아요.
userId보단 userEmail하고 username을 반환하는게 좋을 것 같아요

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +                .build();
passwordEncorder channel 도메인에 만들고 password도 추가하면 될 것 같아요

2023-08-07 05:13 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("User not found"));
이런 예외도 있었군요 좋네요!

2023-08-07 05:27 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/entity/ChannelContentType.java
> +    MESSAGE, CALL_OUT, FILE
확인완료

2023-08-07 05:40 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/dto/ChannelContentResponseDto.java
> +    private final Long channelId;
넵

2023-08-07 05:43 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/entity/UserChannel.java
> +    private boolean isAdmin;
확인

2023-08-07 06:49 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/controller/ChannelController.java
넵

2023-08-07 07:29 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +    @Transactional
✅

2023-08-07 07:34 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +    @Transactional
✅

2023-08-07 08:46 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +                .build();
✅

2023-08-07 08:59 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +    }
✅

2023-08-07 09:28 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/user/controller/UserController.java
> +    }
만약 어떤 자유게시판을 생각했을 때, 유저 본인이 작성한 게시글들을 조회한다면 저는 user_id로 찾을 것 같습니다.
비유가 적절한 지 모르겠지만 유저 본인이 참여한 목록들을 조회할 때도 저는 user_id로 찾는게 좋다고 생각했습니다.
그리고 UserChannel에서도 user_id가 왜래키여서 충분히 활용 가능해 보이는데 어떻게 생각하시나요

2023-08-07 09:51 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +                            channelContent.getCalloutContent().getId(),
그런 경우 NullPointerException이 뜨려나요..

2023-08-07 09:56 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +                })
흠 이거는 그냥 둬도 될까요

2023-08-07 09:58 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +    }
✅

2023-08-07 09:59 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +    }
✅

2023-08-07 10:33 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/user/controller/UserController.java
> +    }
@ModelAttribute User user

2023-08-07 10:50 UTC, cornpip requested changes

2023-08-07 10:50 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +        return channelRepository.save(channel);
@Transactional 붙어있으면 영속성 컨텍스트 변경감지로 update가 자동으로 동작해요!

이때 save하면 insert로 나갈지 update로 나갈지는 확인해봐야겠네요
일단 save는 빼는게 좋을 것 같아요

2023-08-07 10:50 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/entity/ChannelContentType.java
> +    MESSAGE, CALL_OUT, FILE
해당 enum 지워도 될 것 같아요

2023-08-07 10:50 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +                            channelContent.getCalloutContent().getId(),
처리되지 않은 예외니까 요청을 실패할 거예요

2023-08-07 10:50 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +    @Transactional
.

2023-08-07 10:50 UTC, cornpip commented on src/main/java/com/innovationcamp/messenger/domain/channel/entity/UserChannel.java
> +    private boolean isAdmin;
.

2023-08-08 23:10 UTC, KH-CHOO commented on src/main/java/com/innovationcamp/messenger/domain/channel/service/ChannelServiceImpl.java
> +                            channelContent.getCalloutContent().getId(),
NullPointerException 뜨는 것 확인했습니다

2023-08-09 05:26 UTC, cornpip approved these changes

2023-08-09 05:26 UTC, merged